test-deploy-marketplace-back:
  stage: deploy
  environment:
    name: test
  script:
    - cd /opt/project/marketplace-back/ && git pull --rebase --autostash && sudo systemctl stop marketplace-back.service && sudo systemctl start marketplace-back.service; sleep 30 && tail -20 /var/log/marketplace-back/marketplace-back.err.log && sudo systemctl status marketplace-back.service
  only:
    - test
  tags:
    - test
  when: manual

test-install requirements:
  stage: deploy
  environment:
    name: test-install-requirements
  script:
    - cd /opt/project/marketplace-back/ && git pull --rebase --autostash && source /opt/project/marketplace-back/venv/bin/activate && pip3 install -r requirements.txt && deactivate
  only:
    - test
  tags:
    - test
  when: manual